"""
Pydantic models for request and response validation.
"""

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, ConfigDict


class ChatRequest(BaseModel):
    """Payload sent by clients (laptop agent or mobile app) to /chat."""
    message: str = Field(..., min_length=1, description="Natural language command or query")
    session_id: str = Field(default="default", description="Conversation session identifier")
    device_id: Optional[str] = Field(default="laptop", description="Source device identifier (e.g. laptop, mobile)")


class ChatResponse(BaseModel):
    """Response returned by /chat."""
    response: str = Field(..., description="Assistant reply generated by LLM")
    session_id: str = Field(..., description="Active conversation session identifier")
    message_id: int = Field(..., description="Database ID of the assistant reply")
    history_count: int = Field(..., description="Number of historical context messages used in the prompt")
    provider: str = Field(..., description="LLM provider that generated the response")


class MessageHistoryItem(BaseModel):
    """Schema for individual message in conversation history."""
    model_config = ConfigDict(from_attributes=True)

    id: int
    role: str
    content: str
    device_id: Optional[str] = None
    created_at: datetime


class SessionHistoryResponse(BaseModel):
    """Schema for /history response."""
    session_id: str
    total_messages: int
    messages: List[MessageHistoryItem]
